"""Build dashboard.css from shared/design/tokens.json.

Run this script whenever tokens.json changes:

    python -m dashboard.build_css

Output: dashboard/static/css/dashboard.css

No hardcoded colors, fonts, or spacing in the output CSS — every value
is derived from the token file. The script emits :root { --var: value; }
CSS custom properties, then semantic classes on top.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

# repo root = two levels up from this file
_REPO_ROOT = Path(__file__).resolve().parent.parent
_TOKENS_PATH = _REPO_ROOT / "shared" / "design" / "tokens.json"
_OUT_PATH = Path(__file__).resolve().parent / "static" / "css" / "dashboard.css"


def _flat(tokens: dict, prefix: str = "") -> dict[str, str]:
    """Flatten nested token dict into CSS variable names → values.

    E.g. {"color": {"bg": {"base": {"value": "#1b2430"}}}}
    → {"--color-bg-base": "#1b2430"}
    """
    result: dict[str, str] = {}
    for key, val in tokens.items():
        # Skip schema / metadata keys
        if key in ("$schema", "name", "description", "version"):
            continue
        css_key = f"{prefix}-{key}" if prefix else key
        if isinstance(val, dict):
            if "value" in val:
                # leaf token
                v = val["value"]
                # CSS var names use hyphens
                var_name = f"--{css_key.replace('.', '-')}"
                result[var_name] = str(v)
            else:
                # recurse
                result.update(_flat(val, css_key))
        # non-dict primitives at top level (e.g. plotly/matplotlib sections) are skipped
    return result


def _build_root_vars(tokens: dict) -> str:
    """Emit :root { ... } block with all token values."""
    flat = _flat(tokens)
    lines = [":root {"]
    for var, val in sorted(flat.items()):
        lines.append(f"  {var}: {val};")
    lines.append("}")
    return "\n".join(lines)


def _build_semantic_classes(tokens: dict) -> str:
    """Emit semantic classes using only CSS variables derived from tokens."""
    # Pull what we need via vars — no hardcoded values
    c = tokens["color"]
    _bg_base = "var(--color-bg-base)"
    _bg_soft = "var(--color-bg-soft)"
    _bg_hero = "var(--color-bg-hero)"
    _border = "var(--color-border-base)"
    _border_dim = "var(--color-border-dim)"
    _border_row = "var(--color-border-row)"
    _text = "var(--color-text-primary)"
    _text_dim = "var(--color-text-dim)"
    _text_mute = "var(--color-text-mute)"
    _ok = "var(--color-status-ok)"
    _warn = "var(--color-status-warn)"
    _crit = "var(--color-status-crit)"
    _shut = "var(--color-status-shut)"
    _alert = "var(--color-status-alert)"
    _ok_fill = "var(--color-alpha-ok-fill)"
    _warn_fill = "var(--color-alpha-warn-fill)"
    _crit_fill = "var(--color-alpha-crit-fill)"
    _alert_fill = "var(--color-alpha-alert-fill)"
    _mono = "var(--typography-fontFamily-mono)"

    # Spacing
    sp1 = "var(--spacing-1)"
    sp2 = "var(--spacing-2)"
    sp3 = "var(--spacing-3)"
    sp4 = "var(--spacing-4)"
    sp5 = "var(--spacing-5)"
    sp6 = "var(--spacing-6)"

    # Font sizes
    fs_tiny = "var(--typography-fontSize-tiny)"
    fs_label = "var(--typography-fontSize-label)"
    fs_body = "var(--typography-fontSize-body)"
    fs_header = "var(--typography-fontSize-header)"
    fs_big = "var(--typography-fontSize-big)"
    fs_kpi = "var(--typography-fontSize-kpi)"
    fs_hero = "var(--typography-fontSize-hero)"

    fw_normal = "var(--typography-fontWeight-normal)"
    fw_medium = "var(--typography-fontWeight-medium)"
    fw_bold = "var(--typography-fontWeight-bold)"

    lh_tight = "var(--typography-lineHeight-tight)"
    lh_normal = "var(--typography-lineHeight-normal)"

    ls_label = "var(--typography-letterSpacing-label)"
    ls_kpi = "var(--typography-letterSpacing-kpi)"
    ls_strong = "var(--typography-letterSpacing-strong)"

    panel_pad = "var(--component-panel-padding)"
    panel_pad_hero = "var(--component-panel-paddingHero)"
    bar_h = "var(--component-bar-height)"
    cell_h = "var(--component-cell-height)"
    cell_gap = "var(--component-cell-gap)"
    radius = "var(--radius-none)"

    css = f"""
/* ============================================================
   MDK FLEET — Dashboard CSS
   Generated by dashboard/build_css.py from shared/design/tokens.json
   DO NOT EDIT THIS FILE DIRECTLY — edit tokens.json and regenerate.
   ============================================================ */

/* --- Reset & base ------------------------------------------ */
*, *::before, *::after {{
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}}

html, body {{
  height: 100%;
  background-color: {_bg_base};
  color: {_text};
  font-family: {_mono};
  font-size: {fs_body};
  font-weight: {fw_normal};
  line-height: {lh_normal};
  -webkit-font-smoothing: antialiased;
}}

a {{
  color: {_ok};
  text-decoration: none;
}}
a:hover {{
  text-decoration: underline;
}}

/* --- Layout scaffolding ------------------------------------ */
.page-wrap {{
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}}

.header-bar {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: {sp2} {sp4};
  border-bottom: 1px solid {_border};
  background-color: {_bg_base};
  font-size: {fs_header};
  font-weight: {fw_bold};
  letter-spacing: {ls_strong};
  text-transform: uppercase;
  position: sticky;
  top: 0;
  z-index: 100;
}}

.header-bar .brand {{
  color: {_ok};
  letter-spacing: {ls_strong};
}}

.header-bar .nav-links {{
  display: flex;
  gap: {sp4};
  font-size: {fs_label};
  letter-spacing: {ls_label};
  text-transform: uppercase;
}}

.header-bar .nav-links a {{
  color: {_text_dim};
}}

.header-bar .nav-links a:hover,
.header-bar .nav-links a.active {{
  color: {_text};
  text-decoration: none;
}}

.header-bar .ts-live {{
  font-size: {fs_tiny};
  color: {_text_mute};
  letter-spacing: {ls_label};
}}

.main-content {{
  flex: 1;
  padding: {sp4};
  overflow: auto;
}}

/* --- Dashboard grid --------------------------------------- */
.dash-grid {{
  display: grid;
  grid-template-columns: 1fr 1fr;
  grid-template-rows: auto;
  gap: {sp3};
}}

.dash-grid .col-left {{
  display: flex;
  flex-direction: column;
  gap: {sp3};
}}

.dash-grid .col-right {{
  display: flex;
  flex-direction: column;
  gap: {sp3};
}}

@media (max-width: 1100px) {{
  .dash-grid {{
    grid-template-columns: 1fr;
  }}
}}

/* --- Panel ------------------------------------------------ */
.panel {{
  background-color: {_bg_soft};
  border: 1px solid {_border};
  border-radius: {radius};
  padding: {panel_pad};
}}

.panel.hero {{
  background-color: {_bg_hero};
  border: 1.5px solid {_ok};
  padding: {panel_pad_hero};
}}

.panel-title {{
  font-size: {fs_label};
  font-weight: {fw_bold};
  letter-spacing: {ls_strong};
  text-transform: uppercase;
  color: {_text_dim};
  margin-bottom: {sp3};
  border-bottom: 1px dashed {_border_dim};
  padding-bottom: {sp2};
}}

/* --- Fleet map -------------------------------------------- */
.fleet-grid {{
  display: grid;
  grid-template-columns: repeat(10, 1fr);
  gap: {cell_gap};
}}

.miner-cell {{
  height: {cell_h};
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: {fs_tiny};
  font-weight: {fw_medium};
  border: 1px solid {_border_dim};
  border-radius: {radius};
  cursor: pointer;
  transition: opacity 0.15s;
  letter-spacing: 0;
  line-height: 1;
  text-decoration: none;
}}

.miner-cell:hover {{
  opacity: 0.8;
  text-decoration: none;
}}

.miner-cell.status-ok {{
  background-color: {_ok_fill};
  color: {_ok};
  border-color: {_ok};
}}

.miner-cell.status-warn {{
  background-color: {_warn_fill};
  color: {_warn};
  border-color: {_warn};
}}

.miner-cell.status-imm {{
  background-color: {_crit_fill};
  color: {_crit};
  border-color: {_crit};
}}

.miner-cell.status-shut {{
  background-color: transparent;
  color: {_shut};
  border-color: {_shut};
}}

/* --- KPI bars --------------------------------------------- */
.kpi-bar-row {{
  display: flex;
  align-items: center;
  gap: {sp2};
  margin-bottom: {sp1};
}}

.kpi-bar-label {{
  font-size: {fs_tiny};
  color: {_text_dim};
  letter-spacing: {ls_label};
  width: 40px;
  flex-shrink: 0;
}}

.kpi-bar-track {{
  flex: 1;
  height: {bar_h};
  background-color: {_bg_base};
  border: 1px solid {_border_dim};
  border-radius: {radius};
  overflow: hidden;
  position: relative;
}}

.kpi-bar-fill {{
  height: 100%;
  transition: width 0.4s ease;
  border-radius: {radius};
}}

.kpi-bar-fill.te {{
  background-color: {_ok};
}}

.kpi-bar-fill.hsi {{
  background-color: {_warn};
}}

.kpi-bar-value {{
  font-size: {fs_label};
  font-weight: {fw_bold};
  color: {_text};
  width: 40px;
  text-align: right;
  flex-shrink: 0;
}}

/* --- Fleet KPI hero numbers ------------------------------- */
.fleet-kpi-row {{
  display: flex;
  gap: {sp4};
  margin-bottom: {sp3};
}}

.fleet-kpi-block {{
  flex: 1;
  text-align: center;
}}

.fleet-kpi-label {{
  font-size: {fs_tiny};
  color: {_text_dim};
  letter-spacing: {ls_kpi};
  text-transform: uppercase;
  margin-bottom: {sp1};
}}

.fleet-kpi-value {{
  font-size: {fs_kpi};
  font-weight: {fw_bold};
  color: {_ok};
  letter-spacing: {ls_kpi};
}}

.fleet-kpi-value.dim {{
  color: {_warn};
}}

/* --- Env strip -------------------------------------------- */
.env-strip {{
  display: flex;
  gap: {sp4};
  flex-wrap: wrap;
  font-size: {fs_tiny};
  color: {_text_dim};
  letter-spacing: {ls_label};
  padding: {sp2} 0;
  border-top: 1px dashed {_border_dim};
  margin-top: {sp2};
}}

.env-strip .env-item strong {{
  color: {_text};
  font-weight: {fw_medium};
}}

/* --- Flags feed ------------------------------------------- */
.flags-feed {{
  display: flex;
  flex-direction: column;
  gap: 0;
  max-height: 320px;
  overflow-y: auto;
}}

.flag-row {{
  display: flex;
  align-items: flex-start;
  gap: {sp2};
  padding: {sp2} 0;
  border-bottom: 1px dotted {_border_row};
  font-size: {fs_tiny};
  line-height: {lh_tight};
}}

.flag-row:last-child {{
  border-bottom: none;
}}

.flag-severity {{
  font-weight: {fw_bold};
  letter-spacing: {ls_label};
  text-transform: uppercase;
  width: 34px;
  flex-shrink: 0;
}}

.flag-severity.info {{ color: {_text_dim}; }}
.flag-severity.warn {{ color: {_warn}; }}
.flag-severity.crit {{ color: {_crit}; }}

.flag-miner-id {{
  color: {_ok};
  font-weight: {fw_medium};
  width: 36px;
  flex-shrink: 0;
}}

.flag-type {{
  color: {_text};
  flex: 1;
}}

.flag-ts {{
  color: {_text_mute};
  white-space: nowrap;
}}

/* --- Reasoning trace log ---------------------------------- */
.trace-feed {{
  display: flex;
  flex-direction: column;
  gap: 0;
  max-height: 360px;
  overflow-y: auto;
}}

.trace-row {{
  padding: {sp2} 0;
  border-bottom: 1px dotted {_border_row};
  font-size: {fs_tiny};
  line-height: {lh_tight};
}}

.trace-row:last-child {{
  border-bottom: none;
}}

.trace-header {{
  display: flex;
  gap: {sp2};
  align-items: center;
  margin-bottom: {sp1};
}}

.trace-miner {{
  color: {_ok};
  font-weight: {fw_medium};
}}

.trace-action {{
  color: {_warn};
  font-weight: {fw_bold};
  text-transform: uppercase;
  letter-spacing: {ls_label};
}}

.trace-autonomy {{
  color: {_text_mute};
  font-size: {fs_tiny};
}}

.trace-ts {{
  color: {_text_mute};
  margin-left: auto;
  white-space: nowrap;
}}

.trace-reasoning {{
  color: {_text_dim};
  font-size: {fs_tiny};
  margin-top: {sp1};
  padding-left: {sp3};
  border-left: 2px solid {_border_dim};
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  overflow: hidden;
}}

/* --- Status legend ---------------------------------------- */
.legend-row {{
  display: flex;
  gap: {sp4};
  font-size: {fs_tiny};
  color: {_text_dim};
  flex-wrap: wrap;
}}

.legend-item {{
  display: flex;
  align-items: center;
  gap: {sp1};
}}

.legend-dot {{
  width: 8px;
  height: 8px;
  border-radius: {radius};
  flex-shrink: 0;
}}

.legend-dot.ok {{ background-color: {_ok}; }}
.legend-dot.warn {{ background-color: {_warn}; }}
.legend-dot.imm {{ background-color: {_crit}; }}
.legend-dot.shut {{ background-color: {_shut}; }}

/* --- Miner detail page ----------------------------------- */
.miner-detail-header {{
  display: flex;
  align-items: baseline;
  gap: {sp3};
  margin-bottom: {sp4};
}}

.miner-detail-id {{
  font-size: {fs_big};
  font-weight: {fw_bold};
  color: {_text};
  letter-spacing: {ls_kpi};
}}

.miner-detail-status {{
  font-size: {fs_label};
  letter-spacing: {ls_label};
  text-transform: uppercase;
  font-weight: {fw_bold};
}}

.miner-detail-status.ok {{ color: {_ok}; }}
.miner-detail-status.warn {{ color: {_warn}; }}
.miner-detail-status.imm {{ color: {_crit}; }}
.miner-detail-status.shut {{ color: {_shut}; }}

.miner-kpi-grid {{
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: {sp3};
  margin-bottom: {sp4};
}}

.miner-kpi-card {{
  background-color: {_bg_soft};
  border: 1px solid {_border};
  padding: {sp3};
}}

.miner-kpi-card-label {{
  font-size: {fs_tiny};
  color: {_text_dim};
  letter-spacing: {ls_kpi};
  text-transform: uppercase;
  margin-bottom: {sp1};
}}

.miner-kpi-card-value {{
  font-size: {fs_big};
  font-weight: {fw_bold};
  color: {_text};
}}

/* --- Telemetry table -------------------------------------- */
.telemetry-table {{
  width: 100%;
  border-collapse: collapse;
  font-size: {fs_tiny};
}}

.telemetry-table th {{
  text-align: left;
  padding: {sp1} {sp2};
  border-bottom: 1px solid {_border};
  color: {_text_dim};
  letter-spacing: {ls_label};
  text-transform: uppercase;
  font-weight: {fw_medium};
}}

.telemetry-table td {{
  padding: {sp1} {sp2};
  border-bottom: 1px dotted {_border_row};
  color: {_text};
  vertical-align: top;
}}

.telemetry-table tr:hover td {{
  background-color: var(--color-bg-dot);
}}

/* --- Decisions page --------------------------------------- */
.decisions-filter-bar {{
  display: flex;
  gap: {sp3};
  flex-wrap: wrap;
  margin-bottom: {sp4};
  align-items: center;
}}

.decisions-filter-bar label {{
  font-size: {fs_tiny};
  color: {_text_dim};
  letter-spacing: {ls_label};
  text-transform: uppercase;
}}

.decisions-filter-bar input,
.decisions-filter-bar select {{
  background-color: {_bg_soft};
  border: 1px solid {_border_dim};
  color: {_text};
  font-family: {_mono};
  font-size: {fs_tiny};
  padding: {sp1} {sp2};
  border-radius: {radius};
  outline: none;
}}

.decisions-filter-bar input:focus,
.decisions-filter-bar select:focus {{
  border-color: {_border};
}}

.decision-card {{
  background-color: {_bg_soft};
  border: 1px solid {_border};
  padding: {sp3};
  margin-bottom: {sp2};
}}

.decision-card-header {{
  display: flex;
  gap: {sp3};
  align-items: baseline;
  margin-bottom: {sp2};
  flex-wrap: wrap;
}}

.decision-card-miner {{
  color: {_ok};
  font-weight: {fw_bold};
  font-size: {fs_label};
}}

.decision-card-action {{
  color: {_warn};
  font-weight: {fw_bold};
  text-transform: uppercase;
  letter-spacing: {ls_label};
  font-size: {fs_tiny};
}}

.decision-card-autonomy {{
  color: {_text_mute};
  font-size: {fs_tiny};
}}

.decision-card-ts {{
  margin-left: auto;
  color: {_text_mute};
  font-size: {fs_tiny};
}}

.decision-card-agents {{
  font-size: {fs_tiny};
  color: {_text_dim};
  margin-bottom: {sp2};
}}

.decision-card-trace {{
  font-size: {fs_tiny};
  color: {_text_dim};
  padding: {sp2};
  background-color: {_bg_base};
  border-left: 2px solid {_border_dim};
  line-height: {lh_tight};
  white-space: pre-wrap;
  word-break: break-word;
}}

/* --- Utility classes -------------------------------------- */
.text-ok    {{ color: {_ok}; }}
.text-warn  {{ color: {_warn}; }}
.text-crit  {{ color: {_crit}; }}
.text-shut  {{ color: {_shut}; }}
.text-mute  {{ color: {_text_mute}; }}
.text-dim   {{ color: {_text_dim}; }}
.text-alert {{ color: {_alert}; }}

.fw-bold {{ font-weight: {fw_bold}; }}
.fw-medium {{ font-weight: {fw_medium}; }}

.fs-tiny {{ font-size: {fs_tiny}; }}
.fs-label {{ font-size: {fs_label}; }}
.fs-kpi {{ font-size: {fs_kpi}; }}

.mt1 {{ margin-top: {sp1}; }}
.mt2 {{ margin-top: {sp2}; }}
.mt3 {{ margin-top: {sp3}; }}
.mt4 {{ margin-top: {sp4}; }}

.mb1 {{ margin-bottom: {sp1}; }}
.mb2 {{ margin-bottom: {sp2}; }}
.mb3 {{ margin-bottom: {sp3}; }}
.mb4 {{ margin-bottom: {sp4}; }}

.p2 {{ padding: {sp2}; }}
.p3 {{ padding: {sp3}; }}

.border-panel {{ border: 1px solid {_border}; }}

.scrollable {{
  overflow-y: auto;
}}

.live-indicator {{
  display: inline-block;
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: {_ok};
  animation: blink 2s infinite;
  margin-right: {sp1};
}}

@keyframes blink {{
  0%, 100% {{ opacity: 1; }}
  50% {{ opacity: 0.3; }}
}}

.badge {{
  display: inline-block;
  padding: 1px {sp1};
  font-size: {fs_tiny};
  font-weight: {fw_bold};
  letter-spacing: {ls_label};
  text-transform: uppercase;
  border-radius: {radius};
}}

.badge-ok   {{ background-color: {_ok_fill};   color: {_ok};   border: 1px solid {_ok}; }}
.badge-warn {{ background-color: {_warn_fill};  color: {_warn}; border: 1px solid {_warn}; }}
.badge-crit {{ background-color: {_crit_fill};  color: {_crit}; border: 1px solid {_crit}; }}
.badge-alert {{ background-color: {_alert_fill}; color: {_alert}; border: 1px solid {_alert}; }}
.badge-shut {{ color: {_shut}; border: 1px solid {_shut}; }}

/* --- Scrollbar styling ------------------------------------ */
::-webkit-scrollbar {{
  width: 6px;
  height: 6px;
}}
::-webkit-scrollbar-track {{
  background: {_bg_base};
}}
::-webkit-scrollbar-thumb {{
  background: {_border_dim};
  border-radius: {radius};
}}
::-webkit-scrollbar-thumb:hover {{
  background: {_border};
}}
"""
    return css


def build_css() -> None:
    """Read tokens.json, write dashboard.css."""
    if not _TOKENS_PATH.exists():
        print(f"ERROR: tokens.json not found at {_TOKENS_PATH}", file=sys.stderr)
        sys.exit(1)

    tokens = json.loads(_TOKENS_PATH.read_text(encoding="utf-8"))

    root_vars = _build_root_vars(tokens)
    semantic_classes = _build_semantic_classes(tokens)

    out = root_vars + "\n" + semantic_classes

    _OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUT_PATH.write_text(out, encoding="utf-8")
    print(f"Built: {_OUT_PATH}  ({len(out):,} bytes)")


if __name__ == "__main__":
    build_css()
